FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

WORKDIR /app

# Системные зависимости (на случай psycopg2 и т.п.)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Ставим зависимости
COPY requirements.txt .

# Чистим любые старые redis/redis-py-cluster и ставим нормальные версии из requirements.txt
RUN pip uninstall -y redis redis-py-cluster || true \
 && pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# Копируем код проекта
COPY . .

# На всякий случай укажем настройки Django (если Celery их использует)
ENV DJANGO_SETTINGS_MODULE=reservation_System.settings

# Команда по умолчанию (в docker-compose она переопределяется)
CMD ["celery", "-A", "reservation_System", "worker", "-l", "info"]
